Revert "convert to asciidoc at runtime inorder to have user specific content (#155)"
This reverts commit 3b6910c7776abbfbd8ea4f070090cf4c783f7893.

The UI no longer works, and the following error is seen in the console:

docId: 'Deployment type-intro' not valid
AsciidocService.generateHtml @ asciidoc.service.ts?3de8:19
FormComponent.enhanceGui @ wizard.component.ts?bdb8:71
(anonymous) @ wizard.component.ts?bdb8:53
ZoneDelegate.invoke @ zone.js?fad3:391
onInvoke @ core.es5.js?0445:4333
ZoneDelegate.invoke @ zone.js?fad3:390
Zone.run @ zone.js?fad3:141
(anonymous) @ zone.js?fad3:818
ZoneDelegate.invokeTask @ zone.js?fad3:424
onInvokeTask @ core.es5.js?0445:4324
ZoneDelegate.invokeTask @ zone.js?fad3:423
Zone.runTask @ zone.js?fad3:191
drainMicroTaskQueue @ zone.js?fad3:584
ZoneTask.invoke @ zone.js?fad3:490
XMLHttpRequest.send (async)
scheduleTask @ zone.js?fad3:2263
ZoneDelegate.scheduleTask @ zone.js?fad3:410
onScheduleTask @ long-stack-trace-zone.js?fcc3:117
ZoneDelegate.scheduleTask @ zone.js?fad3:404
onScheduleTask @ zone.js?fad3:300
ZoneDelegate.scheduleTask @ zone.js?fad3:404
Zone.scheduleTask @ zone.js?fad3:235
Zone.scheduleMacroTask @ zone.js?fad3:258
(anonymous) @ zone.js?fad3:2287
proto.(anonymous function) @ zone.js?fad3:1426
(anonymous) @ http.es5.js?bb3a:1315
Observable.subscribe @ VM1232:45
subscribeToResult @ VM1254:22
MergeMapSubscriber._innerSub @ VM1284:130
MergeMapSubscriber._tryNext @ VM1284:127
MergeMapSubscriber._next @ VM1284:110
Subscriber.next @ VM1235:89
MapSubscriber._next @ VM1269:83
Subscriber.next @ VM1235:89
(anonymous) @ VM1268:66
ZoneDelegate.invoke @ zone.js?fad3:391
onInvoke @ core.es5.js?0445:4333
ZoneDelegate.invoke @ zone.js?fad3:390
Zone.run @ zone.js?fad3:141
(anonymous) @ zone.js?fad3:818
ZoneDelegate.invokeTask @ zone.js?fad3:424
onInvokeTask @ core.es5.js?0445:4324
ZoneDelegate.invokeTask @ zone.js?fad3:423
Zone.runTask @ zone.js?fad3:191
drainMicroTaskQueue @ zone.js?fad3:584
ZoneTask.invoke @ zone.js?fad3:490
XMLHttpRequest.send (async)
scheduleTask @ zone.js?fad3:2263
ZoneDelegate.scheduleTask @ zone.js?fad3:410
onScheduleTask @ long-stack-trace-zone.js?fcc3:117
ZoneDelegate.scheduleTask @ zone.js?fad3:404
onScheduleTask @ zone.js?fad3:300
ZoneDelegate.scheduleTask @ zone.js?fad3:404
Zone.scheduleTask @ zone.js?fad3:235
Zone.scheduleMacroTask @ zone.js?fad3:258
(anonymous) @ zone.js?fad3:2287
proto.(anonymous function) @ zone.js?fad3:1426
(anonymous) @ http.es5.js?bb3a:1315
Observable.subscribe @ VM1232:45
subscribeToResult @ VM1254:22
MergeMapSubscriber._innerSub @ VM1284:130
MergeMapSubscriber._tryNext @ VM1284:127
MergeMapSubscriber._next @ VM1284:110
Subscriber.next @ VM1235:89
MapSubscriber._next @ VM1269:83
Subscriber.next @ VM1235:89
(anonymous) @ VM1268:66
ZoneDelegate.invoke @ zone.js?fad3:391
onInvoke @ core.es5.js?0445:4333
ZoneDelegate.invoke @ zone.js?fad3:390
Zone.run @ zone.js?fad3:141
(anonymous) @ zone.js?fad3:818
ZoneDelegate.invokeTask @ zone.js?fad3:424
onInvokeTask @ core.es5.js?0445:4324
ZoneDelegate.invokeTask @ zone.js?fad3:423
Zone.runTask @ zone.js?fad3:191
drainMicroTaskQueue @ zone.js?fad3:584
Promise resolved (async)
scheduleMicroTask @ zone.js?fad3:567
ZoneDelegate.scheduleTask @ zone.js?fad3:413
Zone.scheduleTask @ zone.js?fad3:235
Zone.scheduleMicroTask @ zone.js?fad3:255
scheduleResolveOrReject @ zone.js?fad3:816
ZoneAwarePromise.then @ zone.js?fad3:905
(anonymous) @ main.ts?1cec:13
241 @ app.js:100
__webpack_require__ @ polyfills.js:53
758 @ app.js:578
__webpack_require__ @ polyfills.js:53
webpackJsonpCallback @ polyfills.js:24
(anonymous) @ app.js:1

core.es5.js?0445:1289 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'join' of null
TypeError: Cannot read property 'join' of null